feat: add an error message when chart container is not found
chartist-js/chartist pull request #1392
Opened 2022-12-26 11:55 UTC by Arantiryo

Fixes #1354.

Error message example:
![no-container-error-chartist](https://user-images.githubusercontent.com/48175583/209546049-dfaf848c-2893-48d0-acb0-e95e68b4b243.png)

2022-12-26 21:17 UTC, gionkunz commented
Awesome thats long overdue 😂👍

2022-12-26 21:20 UTC, gionkunz commented
In strict typescript container always needs to be defined. I would anyway catch the error earlier before this function call because then you can also print hinting information like the selector that was used.

2022-12-29 12:22 UTC, Arantiryo commented
Good suggestion @gionkunz, thanks for pointing that out! 

Since we can't catch get the selector right before this function call I figured we could modify the error message in the `BaseChart.ts` so the both error messages would look like this:

![no-container-error-msg](https://user-images.githubusercontent.com/48175583/209950488-6e9650d1-a5d9-4267-8bbb-d21247055d91.png)

What do you think?

2022-12-29 20:41 UTC, gionkunz commented
Cool! We had many issues open because people did not understand this error.

What about the size limit check? Do we need to adjust the threshold?

2023-01-04 06:20 UTC, Arantiryo commented
Probably. Let me kindly ask @dangreen about this, he knows way more about CI / CD than I do. :)

2023-01-04 08:06 UTC, dangreen requested changes, later dismissed
@Arantiryo need to edit `.size-limit.json` file, run `pnpm test:size` to run size-limit

2023-01-04 08:06 UTC, dangreen commented on src/charts/BaseChart.ts
> +      );
```suggestion
      throw new Error(
        `Target element ${typeof query === 'string' ? `"${query}"` : ''} is not found`
      );
```

2023-01-04 08:06 UTC, dangreen commented on src/core/creation.ts
>    // Check if there is a previous SVG element in the container that contains the Chartist XML namespace and remove it
```suggestion
  if (!container) {
    throw new Error('Container element is not found');
  }

  // Check if there is a previous SVG element in the container that contains the Chartist XML namespace and remove it
```

2023-01-04 09:21 UTC, gionkunz approved these changes

2023-01-04 13:56 UTC, merged