chore(labels): add option to prevent overlapping labels
chartist-js/chartist pull request #1428
Opened 2024-06-04 12:48 UTC by L-Har

Add an option to pie chart that can prevent overlapping labels. If preventOverlappingLabelOffset is Nonzero check if a label has overlapping text then move it the number of pixels up and left (Should be label size)

2024-06-04 13:08 UTC, L-Har commented
@evertheylen Would you mind taking a look at this pull request? I think this would be a useful option if it were to be added into the main branch.

2024-06-04 13:14 UTC, evertheylen commented
@L-Har the code looks good from a cursory glance but I'm not sure why you're asking me :)

2024-06-04 13:15 UTC, evertheylen approved these changes

2024-06-04 13:27 UTC, L-Har commented
@evertheylen Sorry about that, I thought you were a maintainer. Thanks for approving though

2024-06-04 13:30 UTC, L-Har commented
@gionkunz Would you mind reviewing this pull request?

2025-04-11 15:03 UTC, L-Har commented
@dangreen Hello. Would you mind taking a look at this pull request? It's just an implementation of a way to prevent overlapping labels in the pie chart. With an option to toggle it on if desired, and unit tests.

2025-04-11 15:07 UTC, dangreen commented
@L-Har Could you please rebase fork to fresh master?

2025-04-11 18:30 UTC, L-Har commented
@dangreen Hello Dan, Sure I can. I've went ahead and rebased this branch to main.

2025-04-11 22:23 UTC, dangreen requested changes

2025-04-11 22:23 UTC, dangreen commented on src/charts/PieChart/PieChart.ts
> +        let labelPosition: any;
```suggestion
        let labelPosition: AnchorPosition;
```

2025-04-11 22:23 UTC, dangreen commented on src/charts/PieChart/PieChart.ts
> +    const labelPositions: any[] = [];
```suggestion
    const labelPositions: AnchorPosition[] = [];
```

2025-04-11 22:23 UTC, dangreen commented on src/charts/PieChart/PieChart.ts
> +                ((normalizedData.labels[index] + '') as string)?.length ?? 1; // Default to 1 character length
```suggestion
                String(normalizedData.labels[index]).length ?? 1; // Default to 1 character length
```

2025-04-11 22:23 UTC, dangreen commented on src/charts/PieChart/PieChart.ts
> +            const labelMover = (lp: any, item: any) => {
Please move it to top level and add types

2025-04-14 13:47 UTC, L-Har commented on src/charts/PieChart/PieChart.ts
> +    const labelPositions: any[] = [];
I changed the datatype to Dot here since it's a xy coordinate.

2025-04-14 13:48 UTC, L-Har commented on src/charts/PieChart/PieChart.ts
> +        let labelPosition: any;
Hey dangreen, I went ahead and added the datatype here.

2025-04-14 13:50 UTC, L-Har commented on src/charts/PieChart/PieChart.ts
> +            const labelMover = (lp: any, item: any) => {
@dangreen Alright this has been done. I moved labelMover up and made it a method of the PieChart class and added datatypes. I went ahead and checked the test still looks good with all the datatypes that the label supports and that looks fine.

2025-06-13 21:06 UTC, L-Har commented
Hey Dan, just wondering if I needed to do anything else to get this PR in chartist? I'm not sure about the size-limit automated test failing, but I'll check out that trailing whitespace automated check if needed.

2025-06-13 22:03 UTC, dangreen commented on src/charts/PieChart/PieChart.ts
> +              String(normalizedData.labels[index]).length ?? 1; // Default to 1 character length
I'm not sure what you mean here.

1) i guess `normalizedData.labels[index]` can be undefined, so `String(undefined)` is `'undefined'` and we will have here `'undefined'.length`
2) `0 ?? 1` is `0`. You want `1` if label is undefined? or you want min value to be `1` ?

2025-06-16 16:08 UTC, L-Har commented on src/charts/PieChart/PieChart.ts
> +              String(normalizedData.labels[index]).length ?? 1; // Default to 1 character length
Hey dangreen, thanks for pointing that out. I made it default to 0. Right now the Label type is limited to string | number | Date;
normalizedData.labels is never going to be undefined unless typescript typing restrictions are ignored.

I'm not sure why I added the default value originally. It's been a while, but I don't see much of a problem with it working as a failsafe for now. 

I can speculate it might have been a compiler warning, or a linting process when I tried to push this originally? If you want I can remove it though. Not a problem.

Thanks for checking this out though.

2025-06-27 19:27 UTC, dangreen requested changes
Also please run `pnpm build && pnpm test:size` and increase size in .size-limit.json

2025-06-27 19:27 UTC, dangreen commented on src/charts/PieChart/PieChart.ts
> +  }
```suggestion
  /**
   * Check if a label has overlapping text then move it the number of pixels up and left based on textSize.
   * @param labelPos - Label position that chartist will be checking does not overlap with the list of LabelPositions.
   * @param existingLabelPos - Label position that has already been placed that chartist will check against.
   * @param textOffset - this is configured with preventOverlappingLabelOffset option.
   * @param length - How many characters long the label is.
   */
  moveLabel(
    labelPos: Dot,
    existingLabelPos: Dot,
    textOffset: number,
    length: number
  ) {
    if (
      labelPos.y > existingLabelPos.y - textOffset &&
      labelPos.y < existingLabelPos.y + textOffset &&
      labelPos.x > existingLabelPos.x - length * textOffset &&
      labelPos.x < existingLabelPos.x + length * textOffset
    ) {
      labelPos.y -= textOffset;
      labelPos.x -= textOffset;
      this.moveLabel(labelPos, existingLabelPos, textOffset, length);
    }
  }
```

2025-06-27 19:27 UTC, dangreen commented on src/charts/PieChart/PieChart.ts
> +          }
```suggestion
          if (options.preventOverlappingLabelOffset) {
            const textOffset = options.preventOverlappingLabelOffset;
            const length = String(normalizedData.labels[index]).length;

            labelPositions.forEach(item => {
              this.moveLabel(labelPosition, item, textOffset, length);
            });
            labelPositions.push(labelPosition);
          }
```

2025-06-27 19:50 UTC, L-Har commented
@dangreen Of course. Thanks for the tip on the size-limit. And the refactoring. It looked good. I squashed the commits and pushed the changes.

2025-06-27 19:53 UTC, L-Har reviewed
I like the suggested changes.

2025-06-27 20:01 UTC, merged