fix: prototype pollution vulnerability in extend (CVE-2024-45435)
chartist-js/chartist pull request #1433
Opened 2024-10-02 18:38 UTC by andersk

Fixes #1427.
https://nvd.nist.gov/vuln/detail/CVE-2024-45435
https://gist.github.com/tariqhawis/c67177164d3b7975210caddb25b60d62

2024-10-02 19:07 UTC, tariqhawis commented
Hi @andersk ,

Thank you for your feedback regarding the report. I would like to highlight an additional prototype accessor: `constructor.prototype`. A potential injection could look like this:

`extend ({}, JSON.parse('{"constructor":{"prototype":{"polluted":yes}}}'))"`

Checking for the presence of `constructor` in the input should be sufficient. 

Best,
Tariq

2024-10-02 20:49 UTC, andersk commented
> Checking for the presence of `constructor` in the input should be sufficient.

Nope, it’s not.

```js
extend({}, {"hasOwnProperty": {"polluted": "yes"}});
console.log(Object.prototype.hasOwnProperty.polluted); // → yes
```

I’ve pushed a more complete fix.

2025-01-20 05:12 UTC, praveen-zensar approved these changes

2025-01-20 05:16 UTC, praveen-zensar commented
**Please merge this fix as it's a severity score is high. **

2025-02-09 18:07 UTC, danielpalme commented on src/utils/extend.ts
> +      if (targetProto !== null && prop in targetProto) {
I propose the following change for this line:  
`if (prop === "__proto__" || prop === "constructor" || (targetProto !== null && prop in targetProto)) {

See: https://codeql.github.com/codeql-query-help/javascript/js-prototype-pollution-utility/

2025-03-21 15:32 UTC, dangreen approved these changes

2025-03-21 15:36 UTC, dangreen requested changes

2025-03-21 15:36 UTC, dangreen commented on src/utils/extend.ts
>  export function extend(target: any = {}, ...sources: any[]) {
All usage cases are where first argument is empty object. We can rename `extend` to `merge`, remove first argument, and as target use `Object.create(null)`.

I can fix it by myself later on next week

2025-04-07 11:23 UTC, mihaileu commented on src/utils/extend.ts
>  export function extend(target: any = {}, ...sources: any[]) {
seems that @andersk  might not be able to help here

2025-04-07 17:13 UTC, andersk commented on src/utils/extend.ts
>  export function extend(target: any = {}, ...sources: any[]) {
No I agree in principle, but here’s the problem: `Chartist.extend` is part of the public API of this package, and if we bump the semver major version to remove it, that’s going to take years to propagate through the ecosystem…

2025-04-07 17:24 UTC, andersk commented on src/utils/extend.ts
> +      if (targetProto !== null && prop in targetProto) {
This change isn’t necessary because both `__proto__` and `constructor` are already skipped by `targetProto !== null && prop in targetProto`.

2025-04-07 18:02 UTC, dangreen commented
@andersk You should run "update storyshots" action manually in your fork. Then download artifacts and update screenshots in your branch.

2025-04-07 18:08 UTC, andersk commented
@dangreen I did that and it resulted in no changes.

https://github.com/andersk/chartist/actions/runs/14316237387/job/40122907313
https://github.com/andersk/chartist/actions/runs/14316237387/artifacts/2897050220

2025-04-07 18:11 UTC, dangreen commented
@andersk 
put all images from https://github.com/andersk/chartist/actions/runs/14316237387/artifacts/2897050220
to https://github.com/andersk/chartist/tree/main/test/__image_snapshots__

2025-04-07 18:11 UTC, andersk commented
Never mind, figured it out, fixed.

2025-04-07 18:20 UTC, dangreen approved these changes

2025-04-07 18:21 UTC, merged

2025-04-07 19:12 UTC, dangreen commented
https://github.com/chartist-js/chartist/releases/tag/v1.3.1